[package]
name = "nano-mesh-linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-nano-mesh = "0.1.7"
platform-millis = "1.0.0"
platform-millis-linux = "1.0.0"
platform-serial-linux = "1.0.0"
platform-serial = "1.0.1"
lazy_static = "1.4.0"
serialport = "4.0.0"
serial-embedded-hal = "0.1.2"
embedded-hal = "0.2.7"
nb = "1.1.0"
void = "1.0.2"
serial-core = "0.4.0"
ufmt = "0.2.0"
